// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyMoyE1iMBNNgKulPDFXYNtY8dyastOt8',
    appId: '1:17715701951:web:7208cfde011add9fb03e0a',
    messagingSenderId: '17715701951',
    projectId: 'flash-chat-dream-2',
    authDomain: 'flash-chat-dream-2.firebaseapp.com',
    storageBucket: 'flash-chat-dream-2.appspot.com',
    measurementId: 'G-RFL2924PZZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxpp05T5fNH6vMGEMQSqGflQRJZBC1y-c',
    appId: '1:17715701951:android:a1c1c323bef843b7b03e0a',
    messagingSenderId: '17715701951',
    projectId: 'flash-chat-dream-2',
    storageBucket: 'flash-chat-dream-2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjSRJr9-O6MMpEsRF0c5gkuJVy2AJ5D0g',
    appId: '1:17715701951:ios:173d42a2f7f776e2b03e0a',
    messagingSenderId: '17715701951',
    projectId: 'flash-chat-dream-2',
    storageBucket: 'flash-chat-dream-2.appspot.com',
    iosBundleId: 'com.example.flashChatDream2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjSRJr9-O6MMpEsRF0c5gkuJVy2AJ5D0g',
    appId: '1:17715701951:ios:173d42a2f7f776e2b03e0a',
    messagingSenderId: '17715701951',
    projectId: 'flash-chat-dream-2',
    storageBucket: 'flash-chat-dream-2.appspot.com',
    iosBundleId: 'com.example.flashChatDream2',
  );
}
